-- Migration: 028_advanced_purchases_schema.sql
-- Description: Advanced Purchase Orders and Reception Notes schema alignment

ALTER TABLE purchase_orders 
ADD COLUMN IF NOT EXISTS supplier_id UUID REFERENCES providers(id),
ADD COLUMN IF NOT EXISTS supplier_rif VARCHAR(50),
ADD COLUMN IF NOT EXISTS payment_term VARCHAR(50) DEFAULT 'CONTADO',
ADD COLUMN IF NOT EXISTS currency VARCHAR(10) DEFAULT 'USD',
ADD COLUMN IF NOT EXISTS exchange_rate NUMERIC(12, 4) DEFAULT 1.0000,
ADD COLUMN IF NOT EXISTS is_national BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS global_discount_percentage NUMERIC(5, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS global_discount_amount NUMERIC(12, 4) DEFAULT 0,
ADD COLUMN IF NOT EXISTS global_surcharge_percentage NUMERIC(5, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS global_surcharge_amount NUMERIC(12, 4) DEFAULT 0;

ALTER TABLE purchase_reception_notes 
ADD COLUMN IF NOT EXISTS supplier_id UUID REFERENCES providers(id),
ADD COLUMN IF NOT EXISTS supplier_rif VARCHAR(50),
ADD COLUMN IF NOT EXISTS ndr_number VARCHAR(100),
ADD COLUMN IF NOT EXISTS payment_term VARCHAR(50) DEFAULT 'CONTADO',
ADD COLUMN IF NOT EXISTS currency VARCHAR(10) DEFAULT 'USD',
ADD COLUMN IF NOT EXISTS exchange_rate NUMERIC(12, 4) DEFAULT 1.0000,
ADD COLUMN IF NOT EXISTS is_national BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS global_discount_amount NUMERIC(12, 4) DEFAULT 0,
ADD COLUMN IF NOT EXISTS global_surcharge_amount NUMERIC(12, 4) DEFAULT 0;

ALTER TABLE purchase_order_items
ADD COLUMN IF NOT EXISTS item_number INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS model VARCHAR(100),
ADD COLUMN IF NOT EXISTS warehouse_id UUID REFERENCES warehouse_location(id),
ADD COLUMN IF NOT EXISTS discount_percentage NUMERIC(5, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS discount_amount NUMERIC(12, 4) DEFAULT 0,
ADD COLUMN IF NOT EXISTS tax_type VARCHAR(20) DEFAULT 'TAXABLE',
ADD COLUMN IF NOT EXISTS additional_tax_amount NUMERIC(12, 4) DEFAULT 0,
ADD COLUMN IF NOT EXISTS line_comment TEXT;

ALTER TABLE purchase_reception_items
ADD COLUMN IF NOT EXISTS item_number INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS model VARCHAR(100),
ADD COLUMN IF NOT EXISTS warehouse_id UUID REFERENCES warehouse_location(id),
ADD COLUMN IF NOT EXISTS quantity_pending NUMERIC(12, 4) DEFAULT 0,
ADD COLUMN IF NOT EXISTS quantity_returned NUMERIC(12, 4) DEFAULT 0,
ADD COLUMN IF NOT EXISTS discount_percentage NUMERIC(5, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS discount_amount NUMERIC(12, 4) DEFAULT 0,
ADD COLUMN IF NOT EXISTS tax_rate NUMERIC(5, 2) DEFAULT 16.00,
ADD COLUMN IF NOT EXISTS tax_amount NUMERIC(12, 4) DEFAULT 0,
ADD COLUMN IF NOT EXISTS net_total NUMERIC(12, 4) DEFAULT 0,
ADD COLUMN IF NOT EXISTS additional_tax_amount NUMERIC(12, 4) DEFAULT 0,
ADD COLUMN IF NOT EXISTS line_comment TEXT,
ADD COLUMN IF NOT EXISTS batch_number VARCHAR(100),
ADD COLUMN IF NOT EXISTS expiration_date TIMESTAMP;

CREATE TABLE IF NOT EXISTS purchase_reception_item_serials (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    reception_item_id UUID NOT NULL REFERENCES purchase_reception_items(id) ON DELETE CASCADE,
    product_id UUID NOT NULL REFERENCES PRODUCTS(id),
    serial_number VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
